### ISSUE TITLE
type

### ISSUE THREAD

**Issue by BuFuuu** [secureworks/family-of-client-ids-research#2]
You wrote:
Here is a simplified diagram of the [authentication code grant flow](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1):

But it needs to be:
Here is a simplified diagram of the [authorization code grant flow](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1):

authentication  vs authorization

**Comment by rcobb-scwx** [comment]
Fixed, thank you for the close read!
